### PR TITLE
Created Contributing.md page

### PR DESCRIPTION
**Pull request by devcer**
Created and added instructions for the page

### CODE REVIEW

**Review by prateekiiest — COMMENTED** [review]
Neatly written. Appreciate that.
I would also like if you could mention how to address issues and how to open a PR for them for those issues.

In case of major modification contributors must first open an issue describing the problem and hence once aproved they should submit their solution as a PR.

Just mention that.

**Comment by devcer** [comment]
Hey, Updated the content. Please check.

**Review by prateekiiest — APPROVED** [review]
Perfect

**Comment by prateekiiest** [comment]
Thanks for the conrtibution @viswanathamsantosh  👍

**Pull request merged**
